id: PA2DD2A1B
initial_creation_type: input
source_metadata:
  title: Nyingma Mönlam Series
  language: fr
  description: 'The following texts are recited during the annual Nyingma Mönlam prayer
    festival in Bodhgaya:'
  volume:
    50d8cf1d8f2e4e8db5f426151656402e:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Eight Auspicious Ones
    9bf1748416e24029aa87f5bf6c9f8a5f:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Bodhisattva Vow
    714db545deec43df9468508a0a331546:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Confession
    da848100591044db8a483d7535b7aa28:
      title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching
        from the Lama Sangdü'
      parent: Seven-Line Prayer
    ba2ae9a6cbf24ad6bf852a020190856b:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Zabtik Drolchok
    14f7d936eb42454ca911e17158acff3f:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Śākyamuni Practice
    ef454ac7a2f040ada1915d96ceda930a:
      title: A Brief Practice for Paying Homage and Making Offerings to the Buddha
        together with his retinue of Arhats
      parent: Sixteen Arhats
    b1b0640c09014abf91c27e0c61515f31:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Guru Rinpoche Visualization
    9056c2de83944655b3c45518a70151ca:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Le'u Dünma
    20c48f8a52e7405587e5eb90a690d3db:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Le'u Dünma
    ae30529dd58d484494dfc7cc7edddfcb:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Le'u Dünma
    e1dde98bb5f943f59ddeb6d57ea73509:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Le'u Dünma
    f2f966a1312f40be825062cf042c5d93:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Le'u Dünma
    50cf87c7f65e4276ab13e5e7493ec2c4:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Le'u Dünma
    fe7becdd38d3430695150bbec9d8e480:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Le'u Dünma
    76cc5e6c065b4ce0b882de32ac2f9308:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Barché Lamsel
    d31a999645a947b2a9e53612b7a37865:
      title: The Prayer in Six Vajra Lines
      parent: Guru Rinpoche Prayers
    ecb82d1cc8124f71ad76bf0070f7a86e:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Guru Rinpoche Prayers
    0de3e5ba57fb44c292f39709ea8daf04:
      title: 'Wisdom''s Bestowal: A Way to Accumulate the Recitation of the Tantra
        ''Chanting the Names of Mañjuśrī'' (Mañjuśrī Nāma Saṃgīti)'
      parent: Chanting the Names of Mañjuśrī
    d48c1e32bf874a6aa7c1344207adc672:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Mañjuśrī
    0c0d775ce29249e4bcfadc2ca83d8cd2:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      parent: Mañjuśrī
    23480a5ae0544afdb2572ba82f756a78:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Heart Sūtra
    145bae6caf9942c4a78468547f2d5c42:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Blazing Wheel
    c6849996ac064328babb3d886eb3c79b:
      title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
      parent: Sitātapatrā
    60809fe2c8cd470db5f2ad58771fdb5d:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Siṃhamukhā
    6e9c683e264440229b6061f9df240525:
      title: The Dhāraṇī of Amitāyus
      parent: Dhāraṇī of Amitāyus
    fbc0e23d6bc64bdfa0ad772c65a3f3a9:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Zangchö Mönlam
    c6c30336fc874d91be8d47c139a5cb0d:
      title: Maitreya's Aspiration
      parent: Maitreya's Aspiration
    fe508d36740247ec895a5715509c75c8:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspiration to Generate Bodhicitta
    a6ab6b62bc714f159059f8f1a0a1269f:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Kunzang Mönlam
    b62e9b986ee04e62afe6e29ba1c815f6:
      title: Brief Sukhāvatī Aspiration
      parent: Amitābha Mönlam
    aaf98110f3ad4be59c4a06397540b7b6:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Amitābha Mönlam
    8bcb7f8bbf42444a9631b41c1b175c1d:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration of Vajradhātu Maṇḍala
    ed898ebed0724f8a9cbbd51ece38e001:
      title: Yeshe Tsogyal's Prayer
      parent: Yeshe Tsogyal’s Prayer
    94b29e67a5e34c92b977bd75a009af21:
      title: Prayer for Dispelling Famine
      parent: Thangtong Gyalpo Prayers
    0cea533c13d643b39318fd773f27b185:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Thangtong Gyalpo Prayers
    1a4acd51e36441e5b1386162adcf0b06:
      title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the
        Omniscient Buddha''s Teachings'
      parent: Sage's Powerful Words of Truth
    bbb0ab6f6cc044f8b437c9abb79a8509:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Rishi's Maledictory Incantation
    f6d64666b86744ccb7a7c70e466fb5a5:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Adamantine Magical Wheel
    5512a08a88ad42c99b747e3e3353a146:
      title: 'The Resounding Drum of Truth: A Prayer and Aspiration'
      parent: Resounding Drum of Truth
    55ddaaf7ed054b51bc4eb80f0e649869:
      title: The Prayer of the Words of Truth
      parent: Words of Truth
    4e13b128fe3b4b2da17386f99c0a0dc8:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Ground, Path & Fruition Prayer
    a43312ab05514633a850041147679bd7:
      title: The Secret Vajra Knot
      parent: Secret Vajra Knot
    855b5822502d43d7833374bdb3973cc7:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Long Life Prayers
    75f64af9663d43109d69b8b6278809e4:
      title: 'The Music of Immortality: A Prayer for the Long Life of His Holiness
        the Dalai Lama'
      parent: Long Life Prayers
    fb73267888c14a259ec40b850dd49a21:
      title: General Long-Life Prayer
      parent: Long Life Prayers
    1ec824141b394bf1848fda7549c296d7:
      title: 'The Melodious Song of Immortality: A Prayer for Long Life'
      parent: Long Life Prayers
    2439ceef7c894a3586345932db18da94:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Prayer for Spread of Nyingma Tradition
    5c46a898e1524a659582c2d745aedf88:
      title: 'Final Words: The Essential Advice'
      parent: Final Words
created_at: '2022-03-01T04:58:16.994127'
last_modified_at: '2022-03-01T04:58:16.994130'
